version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=symphony

  ng:
    build:
      context: .
      dockerfile: ./compose/ng/Dockerfile
    volumes:
      - ./src:/opt/app/src
      - ./config:/opt/app/config
    command: npm start
    ports:
      - "3000:3000"
    links:
      - dotnet:web

  dotnet:
    build:
      context: .
      dockerfile: ./compose/dotnet/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=symphony
    volumes:
      - .:/opt
    ports:
      - "5000:5000"